# Generated by Django 3.1 on 2020-08-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('bio', models.TextField()),
                ('image', models.FilePathField(path='/img')),
                ('video', models.FilePathField(path='/img')),
                ('gender', models.CharField(max_length=50)),
                ('looking_for', models.CharField(max_length=50)),
            ],
        ),
    ]
